name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -U discord.py-self python-slugify pyinstaller
    - name: Create package
      run: |
        pyinstaller --onefile main.py
    - name: Create a release
      run: |
        gh release create ${{ inputs.version }} ./dist/* --generate-notes -t "Release ${{ inputs.version }}" -R ${{github.repository}}
      env:
        GITHUB_TOKEN: ${{ secrets.GH_RELEASE }}
